package com.mjly.bean;

public class TUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.name
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.age
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.pwd
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.adddress
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	private String adddress;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id
	 * @return  the value of t_user.id
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id
	 * @param id  the value for t_user.id
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.name
	 * @return  the value of t_user.name
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.name
	 * @param name  the value for t_user.name
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.age
	 * @return  the value of t_user.age
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.age
	 * @param age  the value for t_user.age
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.pwd
	 * @return  the value of t_user.pwd
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.pwd
	 * @param pwd  the value for t_user.pwd
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.adddress
	 * @return  the value of t_user.adddress
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	public String getAdddress() {
		return adddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.adddress
	 * @param adddress  the value for t_user.adddress
	 * @mbg.generated  Wed May 29 14:40:27 CST 2019
	 */
	public void setAdddress(String adddress) {
		this.adddress = adddress;
	}
}